### ISSUE TITLE
Issue-ethereum multi thread mining sample

### ISSUE THREAD

**Issue by ishida0415** [ishida0415/tg#12]
Automated Review Comments
Issues in ether_mining/either_main.go:
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
Issues in ether_mining/readme.md:
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
